apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- deployment.yaml
- ingressroute.yaml
- service.yaml
namespace: prod
images:
- name: hbr.tcloudsoft.com/develop/gitops-webapp
  newTag: d4384f9e
